// desktop/pages/login.vue
<template>
  <AuthShell
    eyebrow="Welcome back"
    subtitle="Sign in to manage your queue, earnings, and public DJ profile."
    title="Log in"
  >
    <form class="auth-form" @submit.prevent="handleSubmit">
      <label class="form-field">
        <span class="form-label">Email</span>
        <input
          v-model="email"
          autocomplete="email"
          class="form-input"
          inputmode="email"
          type="email"
        />
        <p v-if="fieldErrors.email" class="form-error">{{ fieldErrors.email }}</p>
      </label>

      <label class="form-field">
        <span class="form-label">Password</span>
        <input
          v-model="password"
          autocomplete="current-password"
          class="form-input"
          type="password"
        />
        <p v-if="fieldErrors.password" class="form-error">{{ fieldErrors.password }}</p>
      </label>

      <p v-if="formError" class="form-error">{{ formError }}</p>

      <button class="btn btn-primary auth-submit" :disabled="isSubmitting" type="submit">
        {{ isSubmitting ? "Signing in..." : "Sign in" }}
      </button>

      <p class="auth-footer">
        New to RQST?
        <NuxtLink class="auth-link" to="/signup">Create account</NuxtLink>
      </p>
    </form>
  </AuthShell>
</template>

<script setup lang="ts">
import AuthShell from "~/components/AuthShell.vue";
import { validateEmail, validatePassword } from "~/lib/auth-validation";

definePageMeta({
  layout: "auth",
});

const authStore = useAuthStore();
const route = useRoute();

const email = ref("");
const password = ref("");
const fieldErrors = ref<{ email?: string; password?: string }>({});
const formError = ref("");
const isSubmitting = ref(false);

onMounted(() => {
  const emailParam = route.query.email;
  if (typeof emailParam === "string" && emailParam.trim()) {
    email.value = emailParam.trim().toLowerCase();
  }
});

function validateForm() {
  const nextErrors: { email?: string; password?: string } = {};
  const emailError = validateEmail(email.value);
  const passwordError = validatePassword(password.value);

  if (emailError) {
    nextErrors.email = emailError;
  }

  if (passwordError) {
    nextErrors.password = passwordError;
  }

  fieldErrors.value = nextErrors;
  return Object.keys(nextErrors).length === 0;
}

async function handleSubmit() {
  if (!validateForm() || isSubmitting.value) {
    return;
  }

  isSubmitting.value = true;
  formError.value = "";

  try {
    await authStore.signIn(email.value, password.value);
    const redirect = typeof route.query.redirect === "string" ? route.query.redirect : "/home";
    await navigateTo(redirect);
  } catch (error) {
    formError.value = error instanceof Error ? error.message : "Could not sign in. Please try again.";
  } finally {
    isSubmitting.value = false;
  }
}
</script>

<style scoped>
.auth-form {
  display: grid;
  gap: 16px;
}

.auth-submit {
  justify-content: center;
  width: 100%;
}

.auth-footer {
  color: var(--rqst-ink-muted);
  font-size: 0.92rem;
  margin: 4px 0 0;
  text-align: center;
}

.auth-link {
  color: var(--rqst-coral);
  font-weight: 700;
}
</style>

// mobile/app/(auth)/login.tsx
import { useState } from "react";
import { StyleSheet, Text } from "react-native";
import { router } from "expo-router";

import {
  AuthFooterLink,
  AuthFormField,
  AuthScreenShell,
  AuthSubmitButton,
} from "../../src/features/auth/auth-ui";
import { loginSchema, type LoginFormValues } from "../../src/features/auth/schemas";
import { useAuthStore } from "../../src/store/auth";

const initialValues: LoginFormValues = {
  email: "",
  password: "",
};

export default function LoginScreen() {
  const signIn = useAuthStore((state) => state.signIn);
  const [values, setValues] = useState(initialValues);
  const [fieldErrors, setFieldErrors] = useState<Partial<Record<keyof LoginFormValues, string>>>({});
  const [formError, setFormError] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);

  function updateField<Key extends keyof LoginFormValues>(key: Key, value: LoginFormValues[Key]) {
    setValues((current) => ({ ...current, [key]: value }));
    setFieldErrors((current) => ({ ...current, [key]: undefined }));
    setFormError("");
  }

  async function handleSubmit() {
    const parsed = loginSchema.safeParse(values);
    if (!parsed.success) {
      const nextErrors: Partial<Record<keyof LoginFormValues, string>> = {};
      for (const issue of parsed.error.issues) {
        const field = issue.path[0];
        if (typeof field === "string" && !nextErrors[field as keyof LoginFormValues]) {
          nextErrors[field as keyof LoginFormValues] = issue.message;
        }
      }
      setFieldErrors(nextErrors);
      return;
    }

    setIsSubmitting(true);
    setFormError("");

    try {
      await signIn(parsed.data.email, parsed.data.password);
      router.replace("/(tabs)/home");
    } catch (error) {
      setFormError(error instanceof Error ? error.message : "Could not sign in. Please try again.");
    } finally {
      setIsSubmitting(false);
    }
  }

  return (
    <AuthScreenShell
      eyebrow="Welcome back"
      subtitle="Sign in to request songs, track your queue, and manage your account."
      title="Log in"
    >
      <AuthFormField
        autoComplete="email"
        error={fieldErrors.email}
        keyboardType="email-address"
        label="Email"
        onChangeText={(email) => updateField("email", email)}
        textContentType="emailAddress"
        value={values.email}
      />
      <AuthFormField
        autoComplete="password"
        error={fieldErrors.password}
        label="Password"
        onChangeText={(password) => updateField("password", password)}
        secureTextEntry
        textContentType="password"
        value={values.password}
      />

      {formError ? <Text style={styles.formError}>{formError}</Text> : null}

      <AuthSubmitButton label="Sign in" loading={isSubmitting} onPress={() => void handleSubmit()} />

      <AuthFooterLink href="/(auth)/register" label="Create account" prompt="New to RQST?" />
    </AuthScreenShell>
  );
}

const styles = StyleSheet.create({
  formError: {
    color: "#B73524",
    fontSize: 14,
    lineHeight: 20,
    textAlign: "center",
  },
});
